version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true # For hot reload in Docker
    restart: unless-stopped
