

services:
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    restart: unless-stopped

  # client:
  #   build:
  #     context: .
  #     dockerfile: client/Dockerfile
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true # For hot reload in Docker
  #   restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app       # Sync your code
      - /app/node_modules   # Keep container's node_modules intact
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
volumes:
  db_data:
