

services:
  api:
    build:
      context: ./api
    container_name: django_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/lunch_club

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app       # Sync your code
      - /app/node_modules   # Keep container's node_modules intact
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: lunch_club
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
volumes:
  postgres_data:
